### ISSUE TITLE
Issue with hlint 2.1

### ISSUE THREAD

**Issue by Leonti** [lunaryorn/vscode-hlint#7]
Extension doesn't start when hlint version is `2.1`.
I think it's because it's because `2.1` doesn't conform to semver standard:
https://github.com/lunaryorn/vscode-hlint/blob/master/src/extension.ts#L427

Cheers!

**Comment by lunaryorn** [comment]
Thank you for this report.  Unfortunately I'm not using Haskell currently and have no time to work on this ticket.  I'd appreciate a patch.

**Comment by lunaryorn** [comment]
Thanks to @smt923 for fixing this issue; I just published 0.5.1 with the fix.
